### ISSUE TITLE
indentation is incorrect. in code snippets

### ISSUE THREAD

**Issue by mtrabelsi** [redxgh/rembg.py#2]
indentation is incorrect in code snippets, should be shifted with (for example) with tabs.

code example should be copied and work without modification! 

<img width="734" alt="Screenshot 2024-07-24 at 16 52 10" src="https://github.com/user-attachments/assets/4a524e4e-77cc-43b3-89fd-58ebe55f582b">

**Comment by redxgh** [comment]
issue resolved
